baseurl = "http://lpkmidzukisekaiindonesia.netlify.app"
metaDataFormat = "yaml"
title = "LPK Midzuki Sekai Indonesia"
theme = "blist"
DefaultContentLanguage = "id"
DefaultContentLanguageInSubdir = false
contentDir = "content" #English"
weight = 1
languageName = "Indonesia"
[languages.id.params]
introTitle = "LPK Midzuki Sekai Indonesia"
introSubtitle = "Website resmi LPK Midzuki Sekai Indonesia"
introPhoto = "/picture.jpg"
logo = "/logo.png"
name = "Top Post"
url = "/en/blog/emoji-support/"
weight = 4
[params]
domain = 'litbang.kalbarprov.go.id'
phone = "(0561) 748881"
address = "Dusun lumbu, Tejorejo, Kec. Ringinarum, Kabupaten Kendal, Jawa Tengah 51356"
email = "lpkmidzukisekai@gmail.com"
darkModeToggle = true
enableSearch = true
searchKeys = "["
copyright = "Copyright © 2023"
favicon = "/favicon.svg"
ascentColor = "bg-customGreen"
frontBundle = "Berita"
frontBundle2 = "Flyers"
frontBundle3 = "Gallery-Kegiatan"
frontBundle4 = "Video"
frontBundle5 = "Link-Terkait"
hideMeta = false
hideOtherLanguages = false
toc = true
hidePageThumbnail = false
introTitle = "LPK Midzuki Sekai Indonesia"
introSubtitle = "Website resmi LPK Midzuki Sekai Indonesia"
[params.comments]
system = "giscus"
repo = ""
repoid = ""
category = ""
categoryid = ""
mapping = ""
strict = ""
reactionsenabled = ""
emitmetadata = ""
inputposition = ""
theme = ""
[params.homepage.social]
title = "Follow me"
description = "I work on everything coding and tweet developer memes"
[build]
writeStats = true
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
unsafe = true

[[languages.id.menu.main]]
identifier = 'beranda'
name = "Beranda"
url = "/"
weight = 1
[[languages.id.menu.main]]
identifier = 'profil'
name = "Profil"
weight = 2
[[languages.id.menu.main]]
identifier = 'informasi'
name = "Informasi"
weight = 3
[[languages.id.menu.main]]
identifier = 'publikasi'
name = "Publikasi"
weight = 4


[[languages.id.menu.main]]
identifier = 'sejarah'
name = "Sejarah"
parent = "profil badan"
url = "/page/sejarah"
weight = 1
[[languages.id.menu.main]]
identifier = 'hki'
name = "HKI"
parent = "pengumuman"
url = "/hki"
weight = 2
[[languages.id.menu.main]]
identifier = 'info jurnal'
name = "Info Jurnal"
parent = "pengumuman"
url = "/info jurnal"
weight = 4
[[languages.id.menu.main]]
identifier = 'lomba inovasi'
name = "Lomba Inovasi"
parent = "pengumuman"
url = "/lomba inovasi"
weight = 5
[[languages.id.menu.main]]
identifier = 'Daftar Online'
name = "Daftar Online"
parent = "Pendaftaran"
url = "https://forms.gle/pQXED5m5zpJ9ZabE6"
weight = 6
[[languages.id.menu.main]]
identifier = 'jurnal'
name = "Jurnal"
parent = "publikasi"
url = "/jurnal/jurnal-borneo-akcaya"
weight = 3
[[languages.id.menu.main]]
identifier = 'flyers'
name = "Flyers"
parent = "publikasi"
url = "/flyers"
weight = 5
[[languages.id.menu.main]]
identifier = 'berita'
name = "Berita"
parent = "publikasi"
url = "/berita"
weight = 1
[[languages.id.menu.main]]
identifier = 'artikel'
name = "Artikel"
parent = "publikasi"
url = "/artikel"
weight = 2
[[languages.id.menu.main]]
identifier = 'gallery kegiatan'
name = "Gallery Kegiatan"
parent = "publikasi"
url = "/gallery kegiatan"
weight = 6
[[languages.id.menu.main]]
identifier = 'template'
name = "Template"
parent = "publikasi"
url = "/template/template"
weight = 5

[[languages.id.menu.main]]
identifier = 'Program Kerja'
name = "Program Kerja"
parent = "informasi"
url = "/program-kerja/program-kerja"
weight = 4

[[languages.id.menu.main]]
identifier = 'pengumuman'
name = "Pengumuman"
parent = "informasi"
url = "/pengumuman/pengumuman"
weight = 2
[[languages.id.menu.main]]
identifier = 'profil badan'
name = "Profil Badan"
parent = "profil"
url = "/profil-badan/profil-badan"
weight = 1
[[languages.id.menu.main]]
identifier = 'penghargaan'
name = "Penghargaan"
parent = "informasi"
url = "/penghargaan/penghargaan"
weight = 5
[[languages.id.menu.main]]
identifier = 'video'
name = "Video"
parent = "publikasi"
url = "/video"
weight = 8
[[languages.id.menu.main]]
identifier = 'kontak'
name = "Kontak"
parent = "informasi"
url = "/kontak/kontak"
weight = 1
[[params.homepage.social.icons]]
website = "twitter"
url = "https://x.com/LpkmidzukiSI?t=XRUF21w1Gaqdxp0TmpgRbA&s=09"
[[params.homepage.social.icons]]
website = "tiktok"
url = "https://www.tiktok.com/@lpkmidzukisekaiindonesia"
[[params.homepage.social.icons]]
website = "youtube"
url = "https://www.youtube.com/@lpkmidzukisekaiindonesia"
[[params.homepage.social.icons]]
website = "instagram"
url = "https://www.instagram.com/lpkmidzuki_kendal/"
[[params.homepage.social.icons]]
website = "facebook"
url = "https://www.facebook.com/Lpkmidzukisekaiindonesia/"
[[params.running_text]]
text = "Selamat Datang di Website Resmi LPK Midzuki Sekai Indonesia"
[[params.sliders.images]]
url = "slider0.png"
extension = "png"
[[params.sliders.images]]
url = "slider1.png"
extension = "png"
[[params.sliders.images]]
url = "slider2.png"
extension = "png"
[[params.sliders.images]]
url = "slider3.png"
extension = "png"
[[params.sliders.images]]
url = "slider4.png"
extension = "png"
[[params.sliders.images]]
url = "slider2.png"
extension = "png"
[[params.sliders.images]]
url = "slider5.png"
extension = "png"
