baseurl = ""
metaDataFormat = "yaml"
title = "LPK Midzuki Sekai Indonesia"
theme = "blist"
DefaultContentLanguage = "id"
DefaultContentLanguageInSubdir = false
contentDir = "content" #English"
weight = 1
languageName = "Indonesia"
[languages.id.params]
introTitle = "LPK Midzuki Sekai Indonesia"
introSubtitle = "Website resmi LPK Midzuki Sekai Indonesia"
introPhoto = "/picture.jpg"
logo = "/logo.png"
name = "Top Post"
url = "/en/blog/emoji-support/"
weight = 4
[params]
domain = 'https://lpkmidzukikendal.vercel.app/'
phone = "082139184575"
address = "Dusun lumbu, Tejorejo, Kec. Ringinarum, Kabupaten Kendal, Jawa Tengah 51356"
email = "lpkmidzukikendal@gmail.com"
darkModeToggle = true
enableSearch = true
searchKeys = "["
copyright = "Copyright © 2024"
favicon = "/favicon.svg"
ascentColor = "bg-customGreen"
frontBundle = "Berita"
frontBundle2 = "Flyers"
frontBundle3 = "Gallery-Kegiatan"
frontBundle4 = "Video"
frontBundle5 = "Link-Terkait"
frontBundle6 = "Aplikasi-Balitbang"
frontBundle7 = "Aplikasi-SPBE"
frontBundle8 = "Aplikasi-Data-Kalbar"
hideMeta = false
hideOtherLanguages = false
toc = true
hidePageThumbnail = false
introTitle = "LPK Midzuki Sekai Indonesia"
introSubtitle = "Website resmi LPK Midzuki Sekai Indonesia"
[params.comments]
system = "giscus"
repo = ""
repoid = ""
category = ""
categoryid = ""
mapping = ""
strict = ""
reactionsenabled = ""
emitmetadata = ""
inputposition = ""
theme = ""
[params.homepage.social]
title = "Follow me"
description = "I work on everything coding and tweet developer memes"
[build]
writeStats = true
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
unsafe = true

[[languages.id.menu.main]]
identifier = 'beranda'
name = "Beranda"
url = "/"
weight = 1
[[languages.id.menu.main]]
identifier = 'profil'
name = "Profil"
weight = 2

[[languages.id.menu.main]]
identifier = 'informasi'
name = "Informasi"
weight = 4

[[languages.id.menu.main]]
identifier = 'publikasi'
name = "Publikasi"
weight = 6


[[languages.id.menu.main]]
identifier = 'sejarah'
name = "Sejarah"
parent = "profil badan"
url = "/page/sejarah"
weight = 1


[[languages.id.menu.main]]
identifier = 'pendaftaran online'
name = "Pendaftaran Online"
parent = "pendaftaran online"
url = "https://forms.gle/pQXED5m5zpJ9ZabE6"
weight = 6

[[languages.id.menu.main]]
identifier = 'jurnal'
name = "Jurnal"
parent = "publikasi"
url = "/jurnal/jurnal-borneo-akcaya"
weight = 3
[[languages.id.menu.main]]
identifier = 'flyers'
name = "Flyers"
parent = "publikasi"
url = "/flyers"
weight = 5
[[languages.id.menu.main]]
identifier = 'berita'
name = "Berita"
parent = "publikasi"
url = "/berita"
weight = 1
[[languages.id.menu.main]]
identifier = 'artikel'
name = "Artikel"
parent = "publikasi"
url = "/artikel"
weight = 2
[[languages.id.menu.main]]
identifier = 'gallery kegiatan'
name = "Gallery Kegiatan"
parent = "publikasi"
url = "/gallery kegiatan"
weight = 6
[[languages.id.menu.main]]
identifier = 'template'
name = "Template"
parent = "publikasi"
url = "/template/template"
weight = 5

[[languages.id.menu.main]]
identifier = 'program kerja'
name = "Program Kerja"
parent = "informasi"
url = "/program-kerja/program-kerja"
weight = 4


[[languages.id.menu.main]]
identifier = 'profil badan'
name = "Profil Badan"
parent = "profil"
url = "/profil-badan/profil-badan"
weight = 1
[[languages.id.menu.main]]
identifier = 'penghargaan'
name = "Penghargaan"
parent = "informasi"
url = "/penghargaan/penghargaan"
weight = 5

[[languages.id.menu.main]]
identifier = 'video'
name = "Video"
parent = "publikasi"
url = "/video"
weight = 8

[[languages.id.menu.main]]
identifier = 'kontak'
name = "Kontak"
parent = "informasi"
url = "/kontak/kontak"
weight = 1
[[params.homepage.social.icons]]
website = "twitter"
url = "https://x.com/Umparlitbang?t=XRUF21w1Gaqdxp0TmpgRbA&s=09"
[[params.homepage.social.icons]]
website = "tiktok"
url = "https://www.tiktok.com/@balitbang_kalbar"
[[params.homepage.social.icons]]
website = "youtube"
url = "https://www.youtube.com/@balitbangkalbar"
[[params.homepage.social.icons]]
website = "instagram"
url = "https://www.instagram.com/balitbang_kalbar/"
[[params.homepage.social.icons]]
website = "facebook"
url = "https://www.facebook.com/litbangkalbar"
[[params.agenda]]
lokasi = "Lapangan Apel LPK Midzuki Sekai Indonesia (Kab.Kendal)."
jamMulai = "07:30"
jamSelesai = "13:00"
judul = "Pembinaan Fisik"
tanggal = "08/03/2025"
hari = "Sabtu"
[[params.agenda]]
lokasi = "Ruang Kelas LPK Midzuki Sekai Indonesia (Kab.Kendal)."
jamMulai = "11:00"
jamSelesai = "12:00"
judul = "Pra Wawancara Job"
tanggal = "11/03/2025"
hari = "Selasa"
[[params.agenda]]
lokasi = "Lapangan Apel LPK Midzuki Sekai Indonesia."
jamMulai = "08:00"
jamSelesai = "12:00"
judul = "Pembinaan Fisik Dan Mental"
tanggal = "22/03/2025"
hari = "Sabtu"
[[params.agenda]]
lokasi = "Ruang Rapat Balitbang Provnsi Kalbar"
jamMulai = "09:00"
jamSelesai = "13:00"
judul = "Pengidentifikasian Inovasi Tingkat SMA, SMK, dan SLB Dalam Rangka Peningkatan Indeks Inovasi Daerah di Provinsi Kalimantan Barat"
tanggal = "31/10/2024"
hari = "Kamis"
[[params.running_text]]
text = "Selamat Datang di Website Resmi LPK Midzuki Sekai Indonesia"
[[params.sliders.images]]
url = "slider0.png"
extension = "png"
[[params.sliders.images]]
url = "slider1.png"
extension = "png"
[[params.sliders.images]]
url = "slider2.png"
extension = "png"
[[params.sliders.images]]
url = "slider3.png"
extension = "png"
[[params.sliders.images]]
url = "slider4.png"
extension = "png"
[[params.sliders.images]]
url = "rumah radang.png"
extension = "png"
[[params.sliders.images]]
url = "slider5.png"
extension = "png"
